### ISSUE TITLE
Give mushroom paste at least one other use

### ISSUE THREAD

**Issue by Qwerty97475** [meeprdib/OdysseyNexus#64]
According to vanilla guidelines, most vanilla items should have at least 2 ways to obtain, and 2 uses, unless it's a special case. 
Potential uses for mushroom paste could be:
- use in crafting for a new food item
- smelting
- composting (definitely do this, maybe alongside one+ other idea though)
- Use instead of clay in some recipes

**Comment by meeprdib** [comment]
Will def make it compostable, and I really love the clay substitute idea too, although I'm thinking I should move that property to the "Mycelial Compound" item. I considered making it a food item, but it just seemed a little gross, and I don't really know what kinda foods it'd be used for anyway. Use in smelting wouldn't make sense considering mushrooms aren't really flammable.

**Comment by meeprdib** [comment]
Feature requests are now being handled outside of github
